[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gocql/gocql"

[[constraint]]
  branch = "master"
  name = "github.com/mainflux/mainflux"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.4.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[prune]
  go-tests = true
  unused-packages = true
